// import './globals.css'
// import { Inter } from 'next/font/google'

import Link from "next/link"

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/contact">Contact</Link></li>
            <li><Link href="/media">Media</Link></li>
          </ul>
          <hr />
        {children}
        <hr />
          <h1 style={{color:'red'}}>Footer</h1>
        </body>
    </html>
  )
}
